# MettleCI template pipeline for Azure DevOps

trigger:
- master

pool:
  #[AGENT_POOL]
  default

# These variables should be set in Azure DevOps, with the passwords kept secret:
#  - IISUsername
#  - IISPassword
#  - MCIUsername
#  - MCIPassword
variables:
  ProjectName: dstage10 # Name of DS project without environment suffix
  MettleHome: /opt/dm/mci
  ComplianceRepo: compliance # Name of compliance repo

stages:

#------------------------------------------------------------------------------
- stage: Deploy_CI
  variables:
    EnvironmentID: ci
    DatastageProject: $(ProjectName)_ci
    ServerName: gummosis1.fyre.ibm.com
    DomainName: gummosis1.fyre.ibm.com:9443
  jobs:
  - template: deploy-template.yml
    parameters:
      DomainName: $(DomainName)
      ServerName: $(ServerName)
      EnvironmentID: $(EnvironmentID)
      EnvironmentName: Continuous_Integration
      DatastageProject: $(DatastageProject)
      ProjectCacheDir: C:\dm\mci\cache\$(ServerName)\$(DatastageProject)
      IISUsername: $(IISUsername)
      IISPassword: $(IISPassword)
      MCIUsername: $(MCIUsername)
      MCIPassword: $(MCIPassword)
      PublishCompilationTests: true
